name: make
on:
  push:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang-tidy
      - run: sudo apt-get install -y python3-pip
      - run: pip3 install cpplint
      - run: make sa
      - run: make FACTOR=40
