name: make
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: self-hosted
    env:
      ImageOS: ubuntu20
    steps:
      - run: sudo mkdir -p /opt/hostedtoolcache && chown $(whoami) /opt/hostedtoolcache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: false
      - run: gem install xcop
      - run: sudo apt-get install -y wget
      - run: | 
          sudo mkdir -p /usr/local/opt
          sudo wget --no-verbose -O /usr/local/opt/Saxon.jar https://repo.maven.apache.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-5/Saxon-HE-9.8.0-5.jar
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y lsb-release
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo snap install powershell --classic
      - uses: egor-tensin/setup-clang@v1
        with:
          version: 13
      - run: sudo apt-get install -y clang-tidy-13 clang-format-13
      - run: |
          for f in clang++ clang-tidy clang-format; do
            if [ -e /usr/bin/${f} ]; then sudo unlink /usr/bin/${f}; fi
            sudo ln -s /usr/bin/${f}-13 /usr/bin/${f}
          done
      - run: pip install cpplint
      - run: sudo apt-get install -y jq
      - run: sudo apt-get install -y cppcheck
      - run: sudo apt-get install -y bc
      - run: sudo apt-get install -y ghc
      - run: sudo apt-get install -y sbcl
#      - run: sudo apt-get install -y linux-tools-generic
#      - run: sudo rm /usr/bin/perf && sudo ln -s /usr/lib/linux-tools/*/perf /usr/bin/perf
      - uses: actions/checkout@v2
      - run: make clean
      - run: make env
      - run: make WANTED=64 index.html
      - run: mkdir gh-pages
      - run: cp index.html gh-pages
      - run: cp index.xml gh-pages
      - run: cp -r reports gh-pages
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
