name: make
on:
  push:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang
      - run: make clean
      - run: make INPUT=27 FACTOR=50
