name: quick make
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo ./ubuntu-install.sh
      - run: make clean
      - run: make env
      - run: make FAST=1
      - run: make sa
