name: quick make
on:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get update -y
      - run: export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get install -y --no-install-recommends tzdata
      - run: sudo apt-get install -y python python3-pip make software-properties-common lsb-release wget
      - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 
      - run: sudo apt-get install -y clang-13 clang-tidy-13 clang-format-13
      - run: sudo apt-get install -y cppcheck bc sbcl rustc ghc
      - run: pip3 install cpplint
      - run: make env
      - run: make FAST=1
      - run: make sa
