name: quick make
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: cl-info
      - uses: actions/setup-go@v2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '22.0.0.2'
          java: 'java11'
      - run: gu install native-image
      - run: pip install cpplint
      - run: apt-get install -y cppcheck
      - run: apt-get install -y bc
      - run: apt-get install -y ghc
      - uses: actions/checkout@v2
      - run: sudo ./ubuntu-install.sh
      - run: make clean
      - run: make env
      - run: make FAST=1
      - run: make sa
