name: quick make
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: gem install xcop
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-go@v2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '22.0.0.2'
          java: 'java11'
      - run: gu install native-image
      - uses: egor-tensin/setup-clang@v1
        with:
          version: 13
      - run: sudo apt-get install -y clang-tidy-13 clang-format-13
      - run: |
          for f in clang++ clang-tidy clang-format; do
            if [ -e /usr/bin/${f} ]; then sudo unlink /usr/bin/${f}; fi
            sudo ln -s /usr/bin/${f}-13 /usr/bin/${f}
          done
      - run: pip install cpplint
      - run: sudo apt-get install -y cppcheck
      - run: sudo apt-get install -y bc
      - run: sudo apt-get install -y ghc
      - run: sudo apt-get install -y sbcl
      - uses: actions/checkout@v2
      - run: make clean
      - run: make env
      - run: make FAST=1
      - run: make sa
