name: quick make
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install -y clang-tidy clang-format cppcheck bc sbcl
      - run: pip install cpplint
      - run: make sa
      - run: make FAST=1
